{{- if .Values.serviceAccount.create -}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wongnai-xds.serviceAccountName" . }}
  labels:
    {{- include "wongnai-xds.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wongnai-xds.serviceAccountName" . }}
  labels:
    {{- include "wongnai-xds.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources:
      - "services"
      - "endpoints"
    verbs:
      - "list"
      - "watch"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wongnai-xds.serviceAccountName" . }}
  labels:
    {{- include "wongnai-xds.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "wongnai-xds.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "wongnai-xds.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}
