# Test values for CI/CD pipeline
deployment:
  image: ghcr.io/wongnai/xds:test

service:
  grpcPort: 5000
  httpPort: 9000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enable for testing
xdsBootstrapConfig:
  enabled: true
  name: xds-bootstrap-config

# Test-specific configurations
podAnnotations:
  test.annotation: "true"

serviceAccount:
  create: true
  name: "test-service-account"
